### PR TITLE
Fix page sizes for LEDGER and TABLOID

### PR DESCRIPTION
**Pull request by Verron**

### CODE REVIEW

**Comment by finwe** [comment]
This PR is flawed on several levels:

* All commits with composer.json changes are completely unnecessary.
* This repo is no official repository for development. See https://github.com/mpdf/mpdf repo.
* What is your source for the updated size? According to https://en.wikipedia.org/wiki/Paper_size#Loose_sizes the former values are correct, unit is a milimetre.

**Comment by Verron** [comment]
The composer.json changes can be removed, but the sizes are NOT in MM.

Based on your source , the size for LETTER should be:

case 'LETTER': {$format = array(216.00,280.00); break;}

And not:

case 'LETTER': {$format = array(612.00,792.00); break;}

If it was in MM. I'll go to the official repo.

**Comment by finwe** [comment]
Oh, i see now, it is multiplied with the scale factor. Can you also round the size to 2 decimal places as all other units are, when you make thr PR to the official repository?

**Comment by Verron** [comment]
I created the PR for the official branch, and added the decimal places. Thanks for the heads up on the official branch.

**Pull request closed without merging**
